services:
  auditiva-db:
    image: mysql:8.0
    container_name: auditiva-db
    command:
      - --log_bin_trust_function_creators=1
      - --default-time-zone=America/New_York
      - --skip-mysqlx
      - --skip-performance-schema
    environment:
      TZ: America/New_York
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    #ports:
    #  - '127.0.0.1:3306:3306'
    volumes:
      - auditiva_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - auditivanet

  auditiva-web:
    build: .
    #image: ghcr.io/audinaaj/auditiva.us:latest
    container_name: auditiva-web
    depends_on:
      auditiva-db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      YII_DEBUG: ${YII_DEBUG:-false}
      COOKIE_KEY: ${COOKIE_KEY}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SERVER: ${MAIL_SERVER}
      DEBUG_IP: ${DEBUG_IP}
      S3_KEY: ${S3_KEY}
      S3_SECRET: ${S3_SECRET}
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount a local directory containing initialization dumps
      # The container will look for /data-init/init.sql on startup
      - ./data-init:/data-init:ro
      #DEV -- mount project dir to /app for live code changes
      - .:/app:delegated
      # Leave some things out for better performance, exclude:
      #   /runtime, /vendor, and web/assets directories
      - /app/runtime
      - /app/vendor
      - /app/web/assets
    #ports:
    #  - '8000:80'
    networks:
      - auditivanet
      - caddynet

volumes:
  auditiva_db_data:

networks:
  auditivanet:
    name: auditivanet
  caddynet:
    external: true
    name: caddynet
