<?php
//------------------------------------------------------------------------------
// USAGE:
// use app\models\UtilsProvider;
// ...
// $form->field($model, 'state')->dropDownList(
//     UtilsProvider::$states,
//     ['prompt'=>'--Select One--']    // options
// );
// $form->field($model, 'country')->dropDownList(
//     UtilsProvider::$countryNames,
//     ['prompt'=>'--Select One--']    // options
// );
//------------------------------------------------------------------------------
namespace app\models;

use Yii;
use yii\base\Model;         // parent for model classes not associated with database tables
//use yii\db\ActiveRecord;  // parent for model classes that do correspond to database tables

/**
 * This is the model class for table "ProviderUtils".
 *
 * @property array $countries
 * @property array $countryNames
 * @property array $languages
 * @property array $states
 */
class UtilsProvider extends Model
{
    // countries_ISO3166_alpha2
    public static $countries = array( 
        'af' => 'Afganistan', 
        'al' => 'Albania', 
        'dz' => 'Algeria', 
        'as' => 'American Samoa', 
        'ad' => 'Andorra', 
        'ao' => 'Angola', 
        'ai' => 'Anguilla', 
        'aq' => 'Antarctica', 
        'ag' => 'Antigua and Barbuda', 
        'ar' => 'Argentina', 
        'am' => 'Armenia', 
        'aw' => 'Aruba', 
        'au' => 'Australia', 
        'at' => 'Austria', 
        'az' => 'Azerbaijan', 
        'bs' => 'Bahamas', 
        'bh' => 'Bahrain', 
        'bd' => 'Bangladesh', 
        'bb' => 'Barbados', 
        'by' => 'Belarus', 
        'be' => 'Belgium', 
        'bz' => 'Belize', 
        'bj' => 'Benin', 
        'bm' => 'Bermuda', 
        'bt' => 'Bhutan', 
        'bo' => 'Bolivia', 
        'ba' => 'Bosnia and Herzegowina', 
        'bw' => 'Botswana', 
        'bv' => 'Bouvet Island', 
        'br' => 'Brazil', 
        'io' => 'British Indian Ocean Territory', 
        'bn' => 'Brunei Darussalam', 
        'bg' => 'Bulgaria', 
        'bf' => 'Burkina Faso', 
        'bi' => 'Burundi', 
        'kh' => 'Cambodia', 
        'cm' => 'Cameroon', 
        'ca' => 'Canada', 
        'cv' => 'Cape Verde', 
        'ky' => 'Cayman Islands', 
        'cf' => 'Central African Republic', 
        'td' => 'Chad', 
        'cl' => 'Chile', 
        'cn' => 'China', 
        'cx' => 'Christmas Island', 
        'cc' => 'Cocos Keeling Islands', 
        'co' => 'Colombia', 
        'km' => 'Comoros', 
        'cg' => 'Congo', 
        'cd' => 'Congo, Democratic Republic of the', 
        'ck' => 'Cook Islands', 
        'cr' => 'Costa Rica', 
        'ci' => 'Cote d\'Ivoire', 
        'hr' => 'Croatia Hrvatska', 
        'cu' => 'Cuba', 
        'cy' => 'Cyprus', 
        'cz' => 'Czech Republic', 
        'dk' => 'Denmark', 
        'dj' => 'Djibouti', 
        'dm' => 'Dominica', 
        'do' => 'Dominican Republic', 
        'tp' => 'East Timor', 
        'ec' => 'Ecuador', 
        'eg' => 'Egypt', 
        'sv' => 'El Salvador', 
        'gq' => 'Equatorial Guinea', 
        'er' => 'Eritrea', 
        'ee' => 'Estonia', 
        'et' => 'Ethiopia', 
        'fk' => 'Falkland Islands Malvinas', 
        'fo' => 'Faroe Islands', 
        'fj' => 'Fiji', 
        'fi' => 'Finland', 
        'fr' => 'France', 
        'fx' => 'France, Metropolitan', 
        'gf' => 'French Guiana', 
        'pf' => 'French Polynesia', 
        'tf' => 'French Southern Territories', 
        'ga' => 'Gabon', 
        'gm' => 'Gambia', 
        'ge' => 'Georgia', 
        'de' => 'Germany', 
        'gh' => 'Ghana', 
        'gi' => 'Gibraltar', 
        'gr' => 'Greece', 
        'gl' => 'Greenland', 
        'gd' => 'Grenada', 
        'gp' => 'Guadeloupe', 
        'gu' => 'Guam', 
        'gt' => 'Guatemala', 
        'gn' => 'Guinea', 
        'gw' => 'Guinea-Bissau', 
        'gy' => 'Guyana', 
        'ht' => 'Haiti', 
        'hm' => 'Heard and Mc Donald Islands', 
        'va' => 'Holy See (Vatican City State)', 
        'hn' => 'Honduras', 
        'hk' => 'Hong Kong', 
        'hu' => 'Hungary', 
        'is' => 'Iceland', 
        'in' => 'India', 
        'id' => 'Indonesia', 
        'ir' => 'Iran, Islamic Republic of', 
        'iq' => 'Iraq', 
        'ie' => 'Ireland', 
        'il' => 'Israel', 
        'it' => 'Italy', 
        'hm' => 'Jamaica', 
        'jp' => 'Japan', 
        'jo' => 'Jordan', 
        'kz' => 'Kazakhstan', 
        'ke' => 'Kenya', 
        'ki' => 'Kiribati', 
        'kp' => 'Korea, Democratic People\'s Republic of', 
        'kr' => 'Korea, Republic of', 
        'kw' => 'Kuwait', 
        'kg' => 'Kyrgyzstan', 
        'la' => 'Lao People\'s Democratic Republic', 
        'lv' => 'Latvia', 
        'lb' => 'Lebanon', 
        'ls' => 'Lesotho', 
        'lr' => 'Liberia', 
        'ly' => 'Libyan Arab Jamahiriya', 
        'li' => 'Liechtenstein', 
        'lt' => 'Lithuania', 
        'lu' => 'Luxembourg', 
        'mo' => 'Macau', 
        'mk' => 'Macedonia, The Former Yugoslav Republic of', 
        'mg' => 'Madagascar', 
        'mw' => 'Malawi', 
        'my' => 'Malaysia', 
        'mv' => 'Maldives', 
        'ml' => 'Mali', 
        'mt' => 'Malta', 
        'mh' => 'Marshall Islands', 
        'mq' => 'Martinique', 
        'mr' => 'Mauritania', 
        'mu' => 'Mauritius', 
        'yt' => 'Mayotte', 
        'mx' => 'Mexico', 
        'fm' => 'Micronesia, Federated States of', 
        'md' => 'Moldova, Republic of', 
        'mc' => 'Monaco', 
        'mn' => 'Mongolia', 
        'ms' => 'Montserrat', 
        'ma' => 'Morocco', 
        'mz' => 'Mozambique', 
        'mm' => 'Myanmar', 
        'na' => 'Namibia', 
        'nr' => 'Nauru', 
        'np' => 'Nepal', 
        'nl' => 'Netherlands', 
        'an' => 'Netherlands Antilles', 
        'nc' => 'New Caledonia', 
        'nz' => 'New Zealand', 
        'ni' => 'Nicaragua', 
        'ne' => 'Niger', 
        'ng' => 'Nigeria', 
        'nu' => 'Niue', 
        'nf' => 'Norfolk Island', 
        'mp' => 'Northern Mariana Islands', 
        'no' => 'Norway', 
        'om' => 'Oman', 
        'pk' => 'Pakistan', 
        'pw' => 'Palau', 
        'pa' => 'Panama', 
        'pg' => 'Papua New Guinea', 
        'py' => 'Paraguay', 
        'pe' => 'Peru', 
        'ph' => 'Philippines', 
        'pn' => 'Pitcairn', 
        'pl' => 'Poland', 
        'pt' => 'Portugal', 
        'pr' => 'Puerto Rico', 
        'qa' => 'Qatar', 
        're' => 'Reunion', 
        'ro' => 'Romania', 
        'ru' => 'Russian Federation', 
        'rw' => 'Rwanda', 
        'kn' => 'Saint Kitts and Nevis', 
        'lc' => 'Saint LUCIA', 
        'vc' => 'Saint Vincent and the Grenadines', 
        'ws' => 'Samoa', 
        'sm' => 'San Marino', 
        'st' => 'Sao Tome and Principe', 
        'sa' => 'Saudi Arabia', 
        'sn' => 'Senegal', 
        'sr' => 'Serbia', 
        'sc' => 'Seychelles', 
        'sl' => 'Sierra Leone', 
        'sg' => 'Singapore', 
        'sk' => 'Slovakia (Slovak Republic)', 
        'si' => 'Slovenia', 
        'sb' => 'Solomon Islands', 
        'so' => 'Somalia', 
        'za' => 'South Africa', 
        'gs' => 'South Georgia and the South Sandwich Islands', 
        'es' => 'Spain', 
        'lk' => 'Sri Lanka', 
        'sh' => 'St. Helena', 
        'pm' => 'St. Pierre and Miquelon', 
        'sd' => 'Sudan', 
        'sr' => 'Suriname', 
        'sj' => 'Svalbard and Jan Mayen Islands', 
        'sz' => 'Swaziland', 
        'se' => 'Sweden', 
        'ch' => 'Switzerland', 
        'sy' => 'Syrian Arab Republic', 
        'tw' => 'Taiwan, Republic of China', 
        'tj' => 'Tajikistan', 
        'tz' => 'Tanzania, United Republic of', 
        'th' => 'Thailand', 
        'tg' => 'Togo', 
        'tk' => 'Tokelau', 
        'to' => 'Tonga', 
        'tt' => 'Trinidad and Tobago', 
        'tn' => 'Tunisia', 
        'tr' => 'Turkey', 
        'tm' => 'Turkmenistan', 
        'tc' => 'Turks and Caicos Islands', 
        'tv' => 'Tuvalu', 
        'ug' => 'Uganda', 
        'ua' => 'Ukraine', 
        'ae' => 'United Arab Emirates', 
        'gb' => 'United Kingdom', 
        'us' => 'United States', 
        'um' => 'United States Minor Outlying Islands', 
        'uy' => 'Uruguay', 
        'uz' => 'Uzbekistan', 
        'vu' => 'Vanuatu', 
        've' => 'Venezuela', 
        'vn' => 'Viet Nam', 
        'vg' => 'Virgin Islands (British)', 
        'vi' => 'Virgin Islands (U.S.)', 
        'wf' => 'Wallis and Futuna Islands', 
        'eh' => 'Western Sahara', 
        'ye' => 'Yemen', 
        'yu' => 'Yugoslavia', 
        'zm' => 'Zambia', 
        'zw' => 'Zimbabwe' 
    ); 
    
    public static $countries_ISO3166_alpha2 = array( 
        'af' => 'Afganistan', 
        'al' => 'Albania', 
        'dz' => 'Algeria', 
        'as' => 'American Samoa', 
        'ad' => 'Andorra', 
        'ao' => 'Angola', 
        'ai' => 'Anguilla', 
        'aq' => 'Antarctica', 
        'ag' => 'Antigua and Barbuda', 
        'ar' => 'Argentina', 
        'am' => 'Armenia', 
        'aw' => 'Aruba', 
        'au' => 'Australia', 
        'at' => 'Austria', 
        'az' => 'Azerbaijan', 
        'bs' => 'Bahamas', 
        'bh' => 'Bahrain', 
        'bd' => 'Bangladesh', 
        'bb' => 'Barbados', 
        'by' => 'Belarus', 
        'be' => 'Belgium', 
        'bz' => 'Belize', 
        'bj' => 'Benin', 
        'bm' => 'Bermuda', 
        'bt' => 'Bhutan', 
        'bo' => 'Bolivia', 
        'ba' => 'Bosnia and Herzegowina', 
        'bw' => 'Botswana', 
        'bv' => 'Bouvet Island', 
        'br' => 'Brazil', 
        'io' => 'British Indian Ocean Territory', 
        'bn' => 'Brunei Darussalam', 
        'bg' => 'Bulgaria', 
        'bf' => 'Burkina Faso', 
        'bi' => 'Burundi', 
        'kh' => 'Cambodia', 
        'cm' => 'Cameroon', 
        'ca' => 'Canada', 
        'cv' => 'Cape Verde', 
        'ky' => 'Cayman Islands', 
        'cf' => 'Central African Republic', 
        'td' => 'Chad', 
        'cl' => 'Chile', 
        'cn' => 'China', 
        'cx' => 'Christmas Island', 
        'cc' => 'Cocos Keeling Islands', 
        'co' => 'Colombia', 
        'km' => 'Comoros', 
        'cg' => 'Congo', 
        'cd' => 'Congo, Democratic Republic of the', 
        'ck' => 'Cook Islands', 
        'cr' => 'Costa Rica', 
        'ci' => 'Cote d\'Ivoire', 
        'hr' => 'Croatia Hrvatska', 
        'cu' => 'Cuba', 
        'cy' => 'Cyprus', 
        'cz' => 'Czech Republic', 
        'dk' => 'Denmark', 
        'dj' => 'Djibouti', 
        'dm' => 'Dominica', 
        'do' => 'Dominican Republic', 
        //'tp' => 'East Timor',  // changed to Timor-Leste 
        'tl' => 'Timor-Leste',  
        'ec' => 'Ecuador', 
        'eg' => 'Egypt', 
        'sv' => 'El Salvador', 
        'gq' => 'Equatorial Guinea', 
        'er' => 'Eritrea', 
        'ee' => 'Estonia', 
        'et' => 'Ethiopia', 
        'fk' => 'Falkland Islands Malvinas', 
        'fo' => 'Faroe Islands', 
        'fj' => 'Fiji', 
        'fi' => 'Finland', 
        'fr' => 'France', 
        'fx' => 'France, Metropolitan', 
        'gf' => 'French Guiana', 
        'pf' => 'French Polynesia', 
        'tf' => 'French Southern Territories', 
        'ga' => 'Gabon', 
        'gm' => 'Gambia', 
        'ge' => 'Georgia', 
        'de' => 'Germany', 
        'gh' => 'Ghana', 
        'gi' => 'Gibraltar', 
        'gr' => 'Greece', 
        'gl' => 'Greenland', 
        'gd' => 'Grenada', 
        'gp' => 'Guadeloupe', 
        'gu' => 'Guam', 
        'gt' => 'Guatemala', 
        'gn' => 'Guinea', 
        'gw' => 'Guinea-Bissau', 
        'gy' => 'Guyana', 
        'ht' => 'Haiti', 
        'hm' => 'Heard and Mc Donald Islands', 
        'va' => 'Holy See (Vatican City State)', 
        'hn' => 'Honduras', 
        'hk' => 'Hong Kong', 
        'hu' => 'Hungary', 
        'is' => 'Iceland', 
        'in' => 'India', 
        'id' => 'Indonesia', 
        'ir' => 'Iran, Islamic Republic of', 
        'iq' => 'Iraq', 
        'ie' => 'Ireland', 
        'il' => 'Israel', 
        'it' => 'Italy', 
        'jm' => 'Jamaica', 
        'jp' => 'Japan', 
        'jo' => 'Jordan', 
        'kz' => 'Kazakhstan', 
        'ke' => 'Kenya', 
        'ki' => 'Kiribati', 
        'kp' => 'Korea, Democratic People\'s Republic of', 
        'kr' => 'Korea, Republic of', 
        'kw' => 'Kuwait', 
        'kg' => 'Kyrgyzstan', 
        'la' => 'Lao People\'s Democratic Republic', 
        'lv' => 'Latvia', 
        'lb' => 'Lebanon', 
        'ls' => 'Lesotho', 
        'lr' => 'Liberia', 
        'ly' => 'Libyan Arab Jamahiriya', 
        'li' => 'Liechtenstein', 
        'lt' => 'Lithuania', 
        'lu' => 'Luxembourg', 
        'mo' => 'Macau', 
        'mk' => 'Macedonia, The Former Yugoslav Republic of', 
        'mg' => 'Madagascar', 
        'mw' => 'Malawi', 
        'my' => 'Malaysia', 
        'mv' => 'Maldives', 
        'ml' => 'Mali', 
        'mt' => 'Malta', 
        'mh' => 'Marshall Islands', 
        'mq' => 'Martinique', 
        'mr' => 'Mauritania', 
        'mu' => 'Mauritius', 
        'yt' => 'Mayotte', 
        'mx' => 'Mexico', 
        'fm' => 'Micronesia, Federated States of', 
        'md' => 'Moldova, Republic of', 
        'mc' => 'Monaco', 
        'mn' => 'Mongolia', 
        'me' => 'Montenegro', 
        'ms' => 'Montserrat', 
        'ma' => 'Morocco', 
        'mz' => 'Mozambique', 
        'mm' => 'Myanmar', 
        'na' => 'Namibia', 
        'nr' => 'Nauru', 
        'np' => 'Nepal', 
        'nl' => 'Netherlands', 
        'an' => 'Netherlands Antilles', 
        'nc' => 'New Caledonia', 
        'nz' => 'New Zealand', 
        'ni' => 'Nicaragua', 
        'ne' => 'Niger', 
        'ng' => 'Nigeria', 
        'nu' => 'Niue', 
        'nf' => 'Norfolk Island', 
        'mp' => 'Northern Mariana Islands', 
        'no' => 'Norway', 
        'om' => 'Oman', 
        'pk' => 'Pakistan', 
        'pw' => 'Palau', 
        'ps' => 'Palestine, State of', 
        'pa' => 'Panama', 
        'pg' => 'Papua New Guinea', 
        'py' => 'Paraguay', 
        'pe' => 'Peru', 
        'ph' => 'Philippines', 
        'pn' => 'Pitcairn', 
        'pl' => 'Poland', 
        'pt' => 'Portugal', 
        'pr' => 'Puerto Rico', 
        'qa' => 'Qatar', 
        're' => 'Reunion', 
        'ro' => 'Romania', 
        'ru' => 'Russian Federation', 
        'rw' => 'Rwanda', 
        'kn' => 'Saint Kitts and Nevis', 
        'lc' => 'Saint LUCIA', 
        'vc' => 'Saint Vincent and the Grenadines', 
        'ws' => 'Samoa', 
        'sm' => 'San Marino', 
        'st' => 'Sao Tome and Principe', 
        'sa' => 'Saudi Arabia', 
        'sn' => 'Senegal', 
        'rs' => 'Serbia', 
        'sc' => 'Seychelles', 
        'sl' => 'Sierra Leone', 
        'sg' => 'Singapore', 
        'sk' => 'Slovakia (Slovak Republic)', 
        'si' => 'Slovenia', 
        'sb' => 'Solomon Islands', 
        'so' => 'Somalia', 
        'za' => 'South Africa', 
        'gs' => 'South Georgia and the South Sandwich Islands', 
        'ss' => 'South Sudan', 
        'es' => 'Spain', 
        'lk' => 'Sri Lanka', 
        'sh' => 'St. Helena', 
        'pm' => 'St. Pierre and Miquelon', 
        'sd' => 'Sudan', 
        'sr' => 'Suriname', 
        'sj' => 'Svalbard and Jan Mayen Islands', 
        'sz' => 'Swaziland', 
        'se' => 'Sweden', 
        'ch' => 'Switzerland', 
        'sy' => 'Syrian Arab Republic', 
        'tw' => 'Taiwan, Province of China', 
        'tj' => 'Tajikistan', 
        'tz' => 'Tanzania, United Republic of', 
        'th' => 'Thailand', 
        'tg' => 'Togo', 
        'tk' => 'Tokelau', 
        'to' => 'Tonga', 
        'tt' => 'Trinidad and Tobago', 
        'tn' => 'Tunisia', 
        'tr' => 'Turkey', 
        'tm' => 'Turkmenistan', 
        'tc' => 'Turks and Caicos Islands', 
        'tv' => 'Tuvalu', 
        'ug' => 'Uganda', 
        'ua' => 'Ukraine', 
        'ae' => 'United Arab Emirates', 
        'gb' => 'United Kingdom', 
        'us' => 'United States', 
        'um' => 'United States Minor Outlying Islands', 
        'uy' => 'Uruguay', 
        'uz' => 'Uzbekistan', 
        'vu' => 'Vanuatu', 
        've' => 'Venezuela', 
        'vn' => 'Viet Nam', 
        'vg' => 'Virgin Islands (British)', 
        'vi' => 'Virgin Islands (U.S.)', 
        'wf' => 'Wallis and Futuna Islands', 
        'eh' => 'Western Sahara', 
        'ye' => 'Yemen', 
        'yu' => 'Yugoslavia', 
        'zm' => 'Zambia', 
        'zw' => 'Zimbabwe' 
    );
    
    public static $countries_ISO3166_alpha3 = array( 
        'ABW' => 'Aruba', 
        'AFG' => 'Afghanistan', 
        'AGO' => 'Angola', 
        'AIA' => 'Anguilla', 
        'ALA' => '�land Islands', 
        'ALB' => 'Albania', 
        'AND' => 'Andorra', 
        'ARE' => 'United Arab Emirates', 
        'ARG' => 'Argentina', 
        'ARM' => 'Armenia', 
        'ASM' => 'American Samoa', 
        'ATA' => 'Antarctica', 
        'ATF' => 'French Southern Territories', 
        'ATG' => 'Antigua and Barbuda', 
        'AUS' => 'Australia', 
        'AUT' => 'Austria', 
        'AZE' => 'Azerbaijan', 
        'BDI' => 'Burundi', 
        'BEL' => 'Belgium', 
        'BEN' => 'Benin', 
        'BES' => 'Bonaire, Sint Eustatius and Saba', 
        'BFA' => 'Burkina Faso', 
        'BGD' => 'Bangladesh', 
        'BGR' => 'Bulgaria', 
        'BHR' => 'Bahrain', 
        'BHS' => 'Bahamas', 
        'BIH' => 'Bosnia and Herzegovina', 
        'BLM' => 'Saint Barth�lemy', 
        'BLR' => 'Belarus', 
        'BLZ' => 'Belize', 
        'BMU' => 'Bermuda', 
        'BOL' => 'Bolivia, Plurinational State of', 
        'BRA' => 'Brazil', 
        'BRB' => 'Barbados', 
        'BRN' => 'Brunei Darussalam', 
        'BTN' => 'Bhutan', 
        'BVT' => 'Bouvet Island', 
        'BWA' => 'Botswana', 
        'CAF' => 'Central African Republic', 
        'CAN' => 'Canada', 
        'CCK' => 'Cocos (Keeling) Islands', 
        'CHE' => 'Switzerland', 
        'CHL' => 'Chile', 
        'CHN' => 'China', 
        'CIV' => 'C�te d\'Ivoire', 
        'CMR' => 'Cameroon', 
        'COD' => 'Congo, the Democratic Republic of the', 
        'COG' => 'Congo', 
        'COK' => 'Cook Islands', 
        'COL' => 'Colombia', 
        'COM' => 'Comoros', 
        'CPV' => 'Cabo Verde', 
        'CRI' => 'Costa Rica', 
        'CUB' => 'Cuba', 
        'CUW' => 'Cura�ao', 
        'CXR' => 'Christmas Island', 
        'CYM' => 'Cayman Islands', 
        'CYP' => 'Cyprus', 
        'CZE' => 'Czech Republic', 
        'DEU' => 'Germany', 
        'DJI' => 'Djibouti', 
        'DMA' => 'Dominica', 
        'DNK' => 'Denmark', 
        'DOM' => 'Dominican Republic', 
        'DZA' => 'Algeria', 
        'ECU' => 'Ecuador', 
        'EGY' => 'Egypt', 
        'ERI' => 'Eritrea', 
        'ESH' => 'Western Sahara', 
        'ESP' => 'Spain', 
        'EST' => 'Estonia', 
        'ETH' => 'Ethiopia', 
        'FIN' => 'Finland', 
        'FJI' => 'Fiji', 
        'FLK' => 'Falkland Islands (Malvinas)', 
        'FRA' => 'France', 
        'FRO' => 'Faroe Islands', 
        'FSM' => 'Micronesia, Federated States of', 
        'GAB' => 'Gabon', 
        'GBR' => 'United Kingdom', 
        'GEO' => 'Georgia', 
        'GGY' => 'Guernsey', 
        'GHA' => 'Ghana', 
        'GIB' => 'Gibraltar', 
        'GIN' => 'Guinea', 
        'GLP' => 'Guadeloupe', 
        'GMB' => 'Gambia', 
        'GNB' => 'Guinea-Bissau', 
        'GNQ' => 'Equatorial Guinea', 
        'GRC' => 'Greece', 
        'GRD' => 'Grenada', 
        'GRL' => 'Greenland', 
        'GTM' => 'Guatemala', 
        'GUF' => 'French Guiana', 
        'GUM' => 'Guam', 
        'GUY' => 'Guyana', 
        'HKG' => 'Hong Kong', 
        'HMD' => 'Heard Island and McDonald Islands', 
        'HND' => 'Honduras', 
        'HRV' => 'Croatia', 
        'HTI' => 'Haiti', 
        'HUN' => 'Hungary', 
        'IDN' => 'Indonesia', 
        'IMN' => 'Isle of Man', 
        'IND' => 'India', 
        'IOT' => 'British Indian Ocean Territory', 
        'IRL' => 'Ireland', 
        'IRN' => 'Iran, Islamic Republic of', 
        'IRQ' => 'Iraq', 
        'ISL' => 'Iceland', 
        'ISR' => 'Israel', 
        'ITA' => 'Italy', 
        'JAM' => 'Jamaica', 
        'JEY' => 'Jersey', 
        'JOR' => 'Jordan', 
        'JPN' => 'Japan', 
        'KAZ' => 'Kazakhstan', 
        'KEN' => 'Kenya', 
        'KGZ' => 'Kyrgyzstan', 
        'KHM' => 'Cambodia', 
        'KIR' => 'Kiribati', 
        'KNA' => 'Saint Kitts and Nevis', 
        'KOR' => 'Korea, Republic of', 
        'KWT' => 'Kuwait', 
        'LAO' => 'Lao People\'s Democratic Republic', 
        'LBN' => 'Lebanon', 
        'LBR' => 'Liberia', 
        'LBY' => 'Libya', 
        'LCA' => 'Saint Lucia', 
        'LIE' => 'Liechtenstein', 
        'LKA' => 'Sri Lanka', 
        'LSO' => 'Lesotho', 
        'LTU' => 'Lithuania', 
        'LUX' => 'Luxembourg', 
        'LVA' => 'Latvia', 
        'MAC' => 'Macao', 
        'MAF' => 'Saint Martin (French part)', 
        'MAR' => 'Morocco', 
        'MCO' => 'Monaco', 
        'MDA' => 'Moldova, Republic of', 
        'MDG' => 'Madagascar', 
        'MDV' => 'Maldives', 
        'MEX' => 'Mexico', 
        'MHL' => 'Marshall Islands', 
        'MKD' => 'Macedonia, the former Yugoslav Republic of', 
        'MLI' => 'Mali', 
        'MLT' => 'Malta', 
        'MMR' => 'Myanmar', 
        'MNE' => 'Montenegro', 
        'MNG' => 'Mongolia', 
        'MNP' => 'Northern Mariana Islands', 
        'MOZ' => 'Mozambique', 
        'MRT' => 'Mauritania', 
        'MSR' => 'Montserrat', 
        'MTQ' => 'Martinique', 
        'MUS' => 'Mauritius', 
        'MWI' => 'Malawi', 
        'MYS' => 'Malaysia', 
        'MYT' => 'Mayotte', 
        'NAM' => 'Namibia', 
        'NCL' => 'New Caledonia', 
        'NER' => 'Niger', 
        'NFK' => 'Norfolk Island', 
        'NGA' => 'Nigeria', 
        'NIC' => 'Nicaragua', 
        'NIU' => 'Niue', 
        'NLD' => 'Netherlands', 
        'NOR' => 'Norway', 
        'NPL' => 'Nepal', 
        'NRU' => 'Nauru', 
        'NZL' => 'New Zealand', 
        'OMN' => 'Oman', 
        'PAK' => 'Pakistan', 
        'PAN' => 'Panama', 
        'PCN' => 'Pitcairn', 
        'PER' => 'Peru', 
        'PHL' => 'Philippines', 
        'PLW' => 'Palau', 
        'PNG' => 'Papua New Guinea', 
        'POL' => 'Poland', 
        'PRI' => 'Puerto Rico', 
        'PRK' => 'Korea, Democratic People\'s Republic of', 
        'PRT' => 'Portugal', 
        'PRY' => 'Paraguay', 
        'PSE' => 'Palestine, State of', 
        'PYF' => 'French Polynesia', 
        'QAT' => 'Qatar', 
        'REU' => 'R�union', 
        'ROU' => 'Romania', 
        'RUS' => 'Russian Federation', 
        'RWA' => 'Rwanda', 
        'SAU' => 'Saudi Arabia', 
        'SDN' => 'Sudan', 
        'SEN' => 'Senegal', 
        'SGP' => 'Singapore', 
        'SGS' => 'South Georgia and the South Sandwich Islands', 
        'SHN' => 'Saint Helena, Ascension and Tristan da Cunha', 
        'SJM' => 'Svalbard and Jan Mayen', 
        'SLB' => 'Solomon Islands', 
        'SLE' => 'Sierra Leone', 
        'SLV' => 'El Salvador', 
        'SMR' => 'San Marino', 
        'SOM' => 'Somalia', 
        'SPM' => 'Saint Pierre and Miquelon', 
        'SRB' => 'Serbia', 
        'SSD' => 'South Sudan', 
        'STP' => 'Sao Tome and Principe', 
        'SUR' => 'Suriname', 
        'SVK' => 'Slovakia', 
        'SVN' => 'Slovenia', 
        'SWE' => 'Sweden', 
        'SWZ' => 'Swaziland', 
        'SXM' => 'Sint Maarten (Dutch part)', 
        'SYC' => 'Seychelles', 
        'SYR' => 'Syrian Arab Republic', 
        'TCA' => 'Turks and Caicos Islands', 
        'TCD' => 'Chad', 
        'TGO' => 'Togo', 
        'THA' => 'Thailand', 
        'TJK' => 'Tajikistan', 
        'TKL' => 'Tokelau', 
        'TKM' => 'Turkmenistan', 
        'TLS' => 'Timor-Leste', 
        'TON' => 'Tonga', 
        'TTO' => 'Trinidad and Tobago', 
        'TUN' => 'Tunisia', 
        'TUR' => 'Turkey', 
        'TUV' => 'Tuvalu', 
        'TWN' => 'Taiwan, Republic of China', 
        'TZA' => 'Tanzania, United Republic of', 
        'UGA' => 'Uganda', 
        'UKR' => 'Ukraine', 
        'UMI' => 'United States Minor Outlying Islands', 
        'URY' => 'Uruguay', 
        'USA' => 'United States', 
        'UZB' => 'Uzbekistan', 
        'VAT' => 'Holy See (Vatican City State)', 
        'VCT' => 'Saint Vincent and the Grenadines', 
        'VEN' => 'Venezuela, Bolivarian Republic of', 
        'VGB' => 'Virgin Islands, British', 
        'VIR' => 'Virgin Islands, U.S.', 
        'VNM' => 'Viet Nam', 
        'VUT' => 'Vanuatu', 
        'WLF' => 'Wallis and Futuna', 
        'WSM' => 'Samoa', 
        'YEM' => 'Yemen', 
        'ZAF' => 'South Africa', 
        'ZMB' => 'Zambia', 
        'ZWE' => 'Zimbabwe'
    );     
    
    public static $countryNames = array( 
        'Afganistan'                                   => 'Afganistan', 
        'Albania'                                      => 'Albania', 
        'Algeria'                                      => 'Algeria', 
        'American Samoa'                               => 'American Samoa', 
        'Andorra'                                      => 'Andorra', 
        'Angola'                                       => 'Angola', 
        'Anguilla'                                     => 'Anguilla', 
        'Antarctica'                                   => 'Antarctica', 
        'Antigua and Barbuda'                          => 'Antigua and Barbuda', 
        'Argentina'                                    => 'Argentina', 
        'Armenia'                                      => 'Armenia', 
        'Aruba'                                        => 'Aruba', 
        'Australia'                                    => 'Australia', 
        'Austria'                                      => 'Austria', 
        'Azerbaijan'                                   => 'Azerbaijan', 
        'Bahamas'                                      => 'Bahamas', 
        'Bahrain'                                      => 'Bahrain', 
        'Bangladesh'                                   => 'Bangladesh', 
        'Barbados'                                     => 'Barbados', 
        'Belarus'                                      => 'Belarus', 
        'Belgium'                                      => 'Belgium', 
        'Belize'                                       => 'Belize', 
        'Benin'                                        => 'Benin', 
        'Bermuda'                                      => 'Bermuda', 
        'Bhutan'                                       => 'Bhutan', 
        'Bolivia'                                      => 'Bolivia', 
        'Bosnia and Herzegowina'                       => 'Bosnia and Herzegowina', 
        'Botswana'                                     => 'Botswana', 
        'Bouvet Island'                                => 'Bouvet Island', 
        'Brazil'                                       => 'Brazil', 
        'British Indian Ocean Territory'               => 'British Indian Ocean Territory', 
        'Brunei Darussalam'                            => 'Brunei Darussalam', 
        'Bulgaria'                                     => 'Bulgaria', 
        'Burkina Faso'                                 => 'Burkina Faso', 
        'Burundi'                                      => 'Burundi', 
        'Cambodia'                                     => 'Cambodia', 
        'Cameroon'                                     => 'Cameroon', 
        'Canada'                                       => 'Canada', 
        'Cape Verde'                                   => 'Cape Verde', 
        'Cayman Islands'                               => 'Cayman Islands', 
        'Central African Republic'                     => 'Central African Republic', 
        'Chad'                                         => 'Chad', 
        'Chile'                                        => 'Chile', 
        'China'                                        => 'China', 
        'Christmas Island'                             => 'Christmas Island', 
        'Cocos Keeling Islands'                        => 'Cocos Keeling Islands', 
        'Colombia'                                     => 'Colombia', 
        'Comoros'                                      => 'Comoros', 
        'Congo'                                        => 'Congo', 
        'Congo, Democratic Republic of the'            => 'Congo, Democratic Republic of the', 
        'Cook Islands'                                 => 'Cook Islands', 
        'Costa Rica'                                   => 'Costa Rica', 
        'Cote d\'Ivoire'                               => 'Cote d\'Ivoire', 
        'Croatia Hrvatska'                             => 'Croatia Hrvatska', 
        'Cuba'                                         => 'Cuba', 
        'Cyprus'                                       => 'Cyprus', 
        'Czech Republic'                               => 'Czech Republic', 
        'Denmark'                                      => 'Denmark', 
        'Djibouti'                                     => 'Djibouti', 
        'Dominica'                                     => 'Dominica', 
        'Dominican Republic'                           => 'Dominican Republic', 
        'East Timor'                                   => 'East Timor', 
        'Ecuador'                                      => 'Ecuador', 
        'Egypt'                                        => 'Egypt', 
        'El Salvador'                                  => 'El Salvador', 
        'Equatorial Guinea'                            => 'Equatorial Guinea', 
        'Eritrea'                                      => 'Eritrea', 
        'Estonia'                                      => 'Estonia', 
        'Ethiopia'                                     => 'Ethiopia', 
        'Falkland Islands Malvinas'                    => 'Falkland Islands Malvinas', 
        'Faroe Islands'                                => 'Faroe Islands', 
        'Fiji'                                         => 'Fiji', 
        'Finland'                                      => 'Finland', 
        'France'                                       => 'France', 
        'France, Metropolitan'                         => 'France, Metropolitan', 
        'French Guiana'                                => 'French Guiana', 
        'French Polynesia'                             => 'French Polynesia', 
        'French Southern Territories'                  => 'French Southern Territories', 
        'Gabon'                                        => 'Gabon', 
        'Gambia'                                       => 'Gambia', 
        'Georgia'                                      => 'Georgia', 
        'Germany'                                      => 'Germany', 
        'Ghana'                                        => 'Ghana', 
        'Gibraltar'                                    => 'Gibraltar', 
        'Greece'                                       => 'Greece', 
        'Greenland'                                    => 'Greenland', 
        'Grenada'                                      => 'Grenada', 
        'Guadeloupe'                                   => 'Guadeloupe', 
        'Guam'                                         => 'Guam', 
        'Guatemala'                                    => 'Guatemala', 
        'Guinea'                                       => 'Guinea', 
        'Guinea-Bissau'                                => 'Guinea-Bissau', 
        'Guyana'                                       => 'Guyana', 
        'Haiti'                                        => 'Haiti', 
        'Heard and Mc Donald Islands'                  => 'Heard and Mc Donald Islands', 
        'Holy See (Vatican City State)'                => 'Holy See (Vatican City State)', 
        'Honduras'                                     => 'Honduras', 
        'Hong Kong'                                    => 'Hong Kong', 
        'Hungary'                                      => 'Hungary', 
        'Iceland'                                      => 'Iceland', 
        'India'                                        => 'India', 
        'Indonesia'                                    => 'Indonesia', 
        'Iran, Islamic Republic of'                    => 'Iran, Islamic Republic of', 
        'Iraq'                                         => 'Iraq', 
        'Ireland'                                      => 'Ireland', 
        'Israel'                                       => 'Israel', 
        'Italy'                                        => 'Italy', 
        'Jamaica'                                      => 'Jamaica', 
        'Japan'                                        => 'Japan', 
        'Jordan'                                       => 'Jordan', 
        'Kazakhstan'                                   => 'Kazakhstan', 
        'Kenya'                                        => 'Kenya', 
        'Kiribati'                                     => 'Kiribati', 
        'Korea, Democratic People\'s Republic of'      => 'Korea, Democratic People\'s Republic of', 
        'Korea, Republic of'                           => 'Korea, Republic of', 
        'Kosovo'                                       => 'Kosovo, Republic of', 
        'Kuwait'                                       => 'Kuwait', 
        'Kyrgyzstan'                                   => 'Kyrgyzstan', 
        'Lao People\'s Democratic Republic'            => 'Lao People\'s Democratic Republic', 
        'Latvia'                                       => 'Latvia', 
        'Lebanon'                                      => 'Lebanon', 
        'Lesotho'                                      => 'Lesotho', 
        'Liberia'                                      => 'Liberia', 
        'Libyan Arab Jamahiriya'                       => 'Libyan Arab Jamahiriya', 
        'Liechtenstein'                                => 'Liechtenstein', 
        'Lithuania'                                    => 'Lithuania', 
        'Luxembourg'                                   => 'Luxembourg', 
        'Macau'                                        => 'Macau', 
        'Macedonia, The Former Yugoslav Republic of'   => 'Macedonia, The Former Yugoslav Republic of', 
        'Madagascar'                                   => 'Madagascar', 
        'Malawi'                                       => 'Malawi', 
        'Malaysia'                                     => 'Malaysia', 
        'Maldives'                                     => 'Maldives', 
        'Mali'                                         => 'Mali', 
        'Malta'                                        => 'Malta', 
        'Marshall Islands'                             => 'Marshall Islands', 
        'Martinique'                                   => 'Martinique', 
        'Mauritania'                                   => 'Mauritania', 
        'Mauritius'                                    => 'Mauritius', 
        'Mayotte'                                      => 'Mayotte', 
        'Mexico'                                       => 'Mexico', 
        'Micronesia, Federated States of'              => 'Micronesia, Federated States of', 
        'Moldova, Republic of'                         => 'Moldova, Republic of', 
        'Monaco'                                       => 'Monaco', 
        'Mongolia'                                     => 'Mongolia', 
        'Montserrat'                                   => 'Montserrat', 
        'Morocco'                                      => 'Morocco', 
        'Mozambique'                                   => 'Mozambique', 
        'Myanmar'                                      => 'Myanmar', 
        'Namibia'                                      => 'Namibia', 
        'Nauru'                                        => 'Nauru', 
        'Nepal'                                        => 'Nepal', 
        'Netherlands'                                  => 'Netherlands', 
        'Netherlands Antilles'                         => 'Netherlands Antilles', 
        'New Caledonia'                                => 'New Caledonia', 
        'New Zealand'                                  => 'New Zealand', 
        'Nicaragua'                                    => 'Nicaragua', 
        'Niger'                                        => 'Niger', 
        'Nigeria'                                      => 'Nigeria', 
        'Niue'                                         => 'Niue', 
        'Norfolk Island'                               => 'Norfolk Island', 
        'Northern Mariana Islands'                     => 'Northern Mariana Islands', 
        'Norway'                                       => 'Norway', 
        'Oman'                                         => 'Oman', 
        'Pakistan'                                     => 'Pakistan', 
        'Palau'                                        => 'Palau', 
        'Panama'                                       => 'Panama', 
        'Papua New Guinea'                             => 'Papua New Guinea', 
        'Paraguay'                                     => 'Paraguay', 
        'Peru'                                         => 'Peru', 
        'Philippines'                                  => 'Philippines', 
        'Pitcairn'                                     => 'Pitcairn', 
        'Poland'                                       => 'Poland', 
        'Portugal'                                     => 'Portugal', 
        'Puerto Rico'                                  => 'Puerto Rico', 
        'Qatar'                                        => 'Qatar', 
        'Reunion'                                      => 'Reunion', 
        'Romania'                                      => 'Romania', 
        'Russian Federation'                           => 'Russian Federation', 
        'Rwanda'                                       => 'Rwanda', 
        'Saint Kitts and Nevis'                        => 'Saint Kitts and Nevis', 
        'Saint Lucia'                                  => 'Saint Lucia', 
        'Saint Vincent and the Grenadines'             => 'Saint Vincent and the Grenadines', 
        'Samoa'                                        => 'Samoa', 
        'San Marino'                                   => 'San Marino', 
        'Sao Tome and Principe'                        => 'Sao Tome and Principe', 
        'Saudi Arabia'                                 => 'Saudi Arabia', 
        'Senegal'                                      => 'Senegal', 
        'Serbia'                                       => 'Serbia', 
        'Seychelles'                                   => 'Seychelles', 
        'Sierra Leone'                                 => 'Sierra Leone', 
        'Singapore'                                    => 'Singapore', 
        'Slovakia (Slovak Republic)'                   => 'Slovakia (Slovak Republic)', 
        'Slovenia'                                     => 'Slovenia', 
        'Solomon Islands'                              => 'Solomon Islands', 
        'Somalia'                                      => 'Somalia', 
        'South Africa'                                 => 'South Africa', 
        'South Georgia and the South Sandwich Islands' => 'South Georgia and the South Sandwich Islands', 
        'Spain'                                        => 'Spain', 
        'Sri Lanka'                                    => 'Sri Lanka', 
        'St. Helena'                                   => 'St. Helena', 
        'St. Pierre and Miquelon'                      => 'St. Pierre and Miquelon', 
        'Sudan'                                        => 'Sudan', 
        'Suriname'                                     => 'Suriname', 
        'Svalbard and Jan Mayen Islands'               => 'Svalbard and Jan Mayen Islands', 
        'Swaziland'                                    => 'Swaziland', 
        'Sweden'                                       => 'Sweden', 
        'Switzerland'                                  => 'Switzerland', 
        'Syrian Arab Republic'                         => 'Syrian Arab Republic', 
        'Taiwan, Republic of China'                    => 'Taiwan, Republic of China', 
        'Tajikistan'                                   => 'Tajikistan', 
        'Tanzania, United Republic of'                 => 'Tanzania, United Republic of', 
        'Thailand'                                     => 'Thailand', 
        'Togo'                                         => 'Togo', 
        'Tokelau'                                      => 'Tokelau', 
        'Tonga'                                        => 'Tonga', 
        'Trinidad and Tobago'                          => 'Trinidad and Tobago', 
        'Tunisia'                                      => 'Tunisia', 
        'Turkey'                                       => 'Turkey', 
        'Turkmenistan'                                 => 'Turkmenistan', 
        'Turks and Caicos Islands'                     => 'Turks and Caicos Islands', 
        'Tuvalu'                                       => 'Tuvalu', 
        'Uganda'                                       => 'Uganda', 
        'Ukraine'                                      => 'Ukraine', 
        'United Arab Emirates'                         => 'United Arab Emirates', 
        'United Kingdom'                               => 'United Kingdom', 
        'United States'                                => 'United States', 
        'United States Minor Outlying Islands'         => 'United States Minor Outlying Islands', 
        'Uruguay'                                      => 'Uruguay', 
        'Uzbekistan'                                   => 'Uzbekistan', 
        'Vanuatu'                                      => 'Vanuatu', 
        'Venezuela'                                    => 'Venezuela', 
        'Viet Nam'                                     => 'Viet Nam', 
        'Virgin Islands (British)'                     => 'Virgin Islands (British)', 
        'Virgin Islands (U.S.)'                        => 'Virgin Islands (U.S.)', 
        'Wallis and Futuna Islands'                    => 'Wallis and Futuna Islands', 
        'Western Sahara'                               => 'Western Sahara', 
        'Yemen'                                        => 'Yemen', 
        'Yugoslavia'                                   => 'Yugoslavia', 
        'Zambia'                                       => 'Zambia', 
        'Zimbabwe'                                     => 'Zimbabwe' 
    );     

    public static $languages = array( 
        'ab' => 'Abkhazian', 
        'aa' => 'Afar', 
        'af' => 'Afrikaans', 
        'ak' => 'Akan', 
        'sq' => 'Albanian', 
        'am' => 'Amharic', 
        'ar' => 'Arabic', 
        'an' => 'Aragonese', 
        'hy' => 'Armenian', 
        'as' => 'Assamese', 
        'av' => 'Avaric', 
        'ae' => 'Avestan', 
        'ay' => 'Aymara', 
        'az' => 'Azerbaijani', 
        'bm' => 'Bambara', 
        'ba' => 'Bashkir', 
        'eu' => 'Basque', 
        'be' => 'Belarusian', 
        'bn' => 'Bengali', 
        'bh' => 'Bihari', 
        'bi' => 'Bislama', 
        'nb' => 'Bokmal', 
        'bs' => 'Bosnian', 
        'br' => 'Breton', 
        'bg' => 'Bulgarian', 
        'my' => 'Burmese', 
        'ca' => 'Catalan', 
        'km' => 'Central Khmer', 
        'ch' => 'Chamorro', 
        'ce' => 'Chechen', 
        'ny' => 'Chewa', 
        'zh' => 'Chinese', 
        'cu' => 'Church Slavic', 
        'cv' => 'Chuvash', 
        'kw' => 'Cornish', 
        'co' => 'Corsican', 
        'cr' => 'Cree', 
        'hr' => 'Croatian', 
        'cs' => 'Czech', 
        'da' => 'Danish', 
        'dv' => 'Dhivehi', 
        'nl' => 'Dutch', 
        'dz' => 'Dzongkha', 
        'en' => 'English', 
        'eo' => 'Esperanto', 
        'et' => 'Estonian', 
        'ee' => 'Ewe', 
        'fo' => 'Faroese', 
        'fj' => 'Fijian', 
        'fi' => 'Finnish', 
        'fr' => 'French', 
        'ff' => 'Fulah', 
        'gd' => 'Gaelic', 
        'gl' => 'Galician', 
        'lg' => 'Ganda', 
        'ka' => 'Georgian', 
        'de' => 'German', 
        'ki' => 'Gikuyu', 
        'el' => 'Greek', 
        'kl' => 'Greenlandic', 
        'gn' => 'Guarani', 
        'gu' => 'Gujarati', 
        'ht' => 'Haitian', 
        'ha' => 'Hausa', 
        'he' => 'Hebrew', 
        'hz' => 'Herero', 
        'hi' => 'Hindi', 
        'ho' => 'Hiri Motu', 
        'hu' => 'Hungarian', 
        'is' => 'Icelandic', 
        'io' => 'Ido', 
        'ig' => 'Igbo', 
        'id' => 'Indonesian', 
        'ia' => 'Interlingua', 
        'iu' => 'Inuktitut', 
        'ik' => 'Inupiaq', 
        'ga' => 'Irish', 
        'it' => 'Italian', 
        'ja' => 'Japanese', 
        'jv' => 'Javanese', 
        'kn' => 'Kannada', 
        'kr' => 'Kanuri', 
        'ks' => 'Kashmiri', 
        'kk' => 'Kazakh', 
        'rw' => 'Kinyarwanda', 
        'kv' => 'Komi', 
        'kg' => 'Kongo', 
        'ko' => 'Korean', 
        'ku' => 'Kurdish', 
        'kj' => 'Kwanyama', 
        'ky' => 'Kyrgyz', 
        'lo' => 'Lao', 
        'la' => 'Latin', 
        'lv' => 'Latvian', 
        'lb' => 'Letzeburgesch', 
        'li' => 'Limburgan', 
        'ln' => 'Lingala', 
        'lt' => 'Lithuanian', 
        'lu' => 'Luba-Katanga', 
        'mk' => 'Macedonian', 
        'mg' => 'Malagasy', 
        'ms' => 'Malay', 
        'ml' => 'Malayalam', 
        'mt' => 'Maltese', 
        'gv' => 'Manx', 
        'mi' => 'Maori', 
        'mr' => 'Marathi', 
        'mh' => 'Marshallese', 
        'ro' => 'Moldavian', 
        'mn' => 'Mongolian', 
        'na' => 'Nauru', 
        'nv' => 'Navajo', 
        'ng' => 'Ndonga', 
        'ne' => 'Nepali', 
        'nd' => 'North Ndebele', 
        'se' => 'Northern Sami', 
        'no' => 'Norwegian', 
        'nn' => 'Norwegian Nynorsk', 
        'ie' => 'Occidental', 
        'oc' => 'Occitan', 
        'oj' => 'Ojibwa', 
        'or' => 'Oriya', 
        'om' => 'Oromo', 
        'os' => 'Ossetian', 
        'pi' => 'Pali', 
        'fa' => 'Persian', 
        'pl' => 'Polish', 
        'pt' => 'Portuguese', 
        'pa' => 'Punjabi', 
        'ps' => 'Pushto', 
        'qu' => 'Quechua', 
        'ro' => 'Romanian', 
        'rm' => 'Romansh', 
        'rn' => 'Rundi', 
        'ru' => 'Russian', 
        'sm' => 'Samoan', 
        'sg' => 'Sango', 
        'sa' => 'Sanskrit', 
        'sc' => 'Sardinian', 
        'sr' => 'Serbian', 
        'sn' => 'Shona', 
        'ii' => 'Sichuan Yi', 
        'sd' => 'Sindhi', 
        'si' => 'Sinhalese', 
        'sk' => 'Slovak', 
        'sl' => 'Slovenian', 
        'so' => 'Somali', 
        'st' => 'Southern Sotho', 
        'nr' => 'South Ndebele', 
        'es' => 'Spanish', 
        'su' => 'Sundanese', 
        'sw' => 'Swahili', 
        'ss' => 'Swati', 
        'sv' => 'Swedish', 
        'tl' => 'Tagalog', 
        'ty' => 'Tahitian', 
        'tg' => 'Tajik', 
        'ta' => 'Tamil', 
        'tt' => 'Tatar', 
        'te' => 'Telugu', 
        'th' => 'Thai', 
        'bo' => 'Tibetan', 
        'ti' => 'Tigrinya', 
        'to' => 'Tonga', 
        'ts' => 'Tsonga', 
        'tn' => 'Tswana', 
        'tr' => 'Turkish', 
        'tk' => 'Turkmen', 
        'tw' => 'Twi', 
        'uk' => 'Ukrainian', 
        'ur' => 'Urdu', 
        'ug' => 'Uyghur', 
        'uz' => 'Uzbek', 
        've' => 'Venda', 
        'vi' => 'Vietnamese', 
        'vo' => 'Volapük', 
        'wa' => 'Walloon', 
        'cy' => 'Welsh', 
        'fy' => 'Western Frisian', 
        'wo' => 'Wolof', 
        'xh' => 'Xhosa', 
        'yi' => 'Yiddish', 
        'yo' => 'Yoruba', 
        'za' => 'Zhuang', 
        'zu' => 'Zulu' 
    ); 
    
    public static $states = array(
        "N/A"=> "Not Applicable",
        "AL"=> "AL - Alabama",
        "AK"=> "AK - Alaska",
        "AP"=> "AP - Armed Forces Pacific",
        "AE"=> "AE - Armed Forces Europe",
        "AA"=> "AA - Armed Forces America",
        "AZ"=> "AZ - Arizona",
        "AR"=> "AR - Arkansas",
        "CA"=> "CA - California",
        "CO"=> "CO - Colorado",
        "CT"=> "CT - Connecticut",
        "DC"=> "DC - Washington D.C.",
        "DE"=> "DE - Delaware",
        "FL"=> "FL - Florida",
        "GA"=> "GA - Georgia",
        "GU"=> "GU - Guam",
        "HI"=> "HI - Hawaii",
        "ID"=> "ID - Idaho",
        "IL"=> "IL - Illinois",
        "IN"=> "IN - Indiana",
        "IA"=> "IA - Iowa",
        "KS"=> "KS - Kansas",
        "KY"=> "KY - Kentucky",
        "LA"=> "LA - Louisiana",
        "ME"=> "ME - Maine",
        "MD"=> "MD - Maryland",
        "MA"=> "MA - Massachusetts",
        "MI"=> "MI - Michigan",
        "MN"=> "MN - Minnesota",
        "MS"=> "MS - Mississippi",
        "MO"=> "MO - Missouri",
        "MT"=> "MT - Montana",
        "NE"=> "NE - Nebraska",
        "NV"=> "NV - Nevada",
        "NH"=> "NH - New Hampshire",
        "NJ"=> "NJ - New Jersey",
        "NM"=> "NM - New Mexico",
        "NY"=> "NY - New York",
        "NC"=> "NC - North Carolina",
        "ND"=> "ND - North Dakota",
        "OH"=> "OH - Ohio",
        "OK"=> "OK - Oklahoma",
        "OR"=> "OR - Oregon",
        "PA"=> "PA - Pennsylvania",
        "PR"=> "PR - Puerto Rico",
        "RI"=> "RI - Rhode Island",
        "SC"=> "SC - South Carolina",
        "SD"=> "SD - South Dakota",
        "TN"=> "TN - Tennessee",
        "TX"=> "TX - Texas",
        "UT"=> "UT - Utah",
        "VT"=> "VT - Vermont",
        "VA"=> "VA - Virginia",
        "VI"=> "VI - Virgin Islands",
        "WA"=> "WA - Washington",
        "WV"=> "WV - West Virginia",
        "WI"=> "WI - Wisconsin",
        "WY"=> "WY - Wyoming"
    );
    
    public static $timezones = [
        'Pacific/Midway'                 => '(GMT-11:00) Midway Island'                  ,
        'Pacific/Samoa'                  => '(GMT-11:00) Samoa'                          ,
        'Pacific/Honolulu'               => '(GMT-10:00) Hawaii'                         ,
        'US/Alaska'                      => '(GMT-09:00) Alaska'                         ,
        'America/Los_Angeles'            => '(GMT-08:00) Pacific Time (US & Canada)'     ,
        'America/Tijuana'                => '(GMT-08:00) Tijuana'                        ,
        'US/Arizona'                     => '(GMT-07:00) Arizona'                        ,
        'America/Chihuahua'              => '(GMT-07:00) Chihuahua'                      ,
        'America/Chihuahua'              => '(GMT-07:00) La Paz'                         ,
        'America/Mazatlan'               => '(GMT-07:00) Mazatlan'                       ,
        'US/Mountain'                    => '(GMT-07:00) Mountain Time (US & Canada)',
        'America/Managua'                => '(GMT-06:00) Central America'                ,
        'US/Central'                     => '(GMT-06:00) Central Time (US & Canada)'     ,
        'America/Mexico_City'            => '(GMT-06:00) Guadalajara'                    ,
        'America/Mexico_City'            => '(GMT-06:00) Mexico City'                    ,
        'America/Monterrey'              => '(GMT-06:00) Monterrey'                      ,
        'Canada/Saskatchewan'            => '(GMT-06:00) Saskatchewan'                   ,
        'America/Bogota'                 => '(GMT-05:00) Bogota'                         ,
        'US/Eastern'                     => '(GMT-05:00) Eastern Time (US & Canada)'     ,
        'US/East-Indiana'                => '(GMT-05:00) Indiana (East)'                 ,
        'America/Lima'                   => '(GMT-05:00) Lima'                           ,
        'America/Bogota'                 => '(GMT-05:00) Quito'                          ,
        'Canada/Atlantic'                => '(GMT-04:00) Atlantic Time (Canada)'         ,
        'America/Caracas'                => '(GMT-04:30) Caracas'                        ,
        'America/La_Paz'                 => '(GMT-04:00) La Paz'                         ,
        'America/Santiago'               => '(GMT-04:00) Santiago'                       ,
        'Canada/Newfoundland'            => '(GMT-03:30) Newfoundland'                   ,
        'America/Sao_Paulo'              => '(GMT-03:00) Brasilia'                       ,
        'America/Argentina/Buenos_Aires' => '(GMT-03:00) Buenos Aires'                   ,
        'America/Argentina/Buenos_Aires' => '(GMT-03:00) Georgetown'                     ,
        'America/Godthab'                => '(GMT-03:00) Greenland'                      ,
        'America/Noronha'                => '(GMT-02:00) Mid-Atlantic'                   ,
        'Atlantic/Azores'                => '(GMT-01:00) Azores'                         ,
        'Atlantic/Cape_Verde'            => '(GMT-01:00) Cape Verde Is.'                 ,
        'Africa/Casablanca'              => '(GMT+00:00) Casablanca'                     ,
        'Europe/London'                  => '(GMT+00:00) Edinburgh'                      ,
        'Etc/Greenwich'                  => '(GMT+00:00) Greenwich Mean Time: Dublin'    ,
        'Europe/Lisbon'                  => '(GMT+00:00) Lisbon'                         ,
        'Europe/London'                  => '(GMT+00:00) London'                         ,
        'Africa/Monrovia'                => '(GMT+00:00) Monrovia'                       ,
        'UTC'                            => '(GMT+00:00) UTC'                            ,
        'Europe/Amsterdam'               => '(GMT+01:00) Amsterdam'                      ,
        'Europe/Belgrade'                => '(GMT+01:00) Belgrade'                       ,
        'Europe/Berlin'                  => '(GMT+01:00) Berlin'                         ,
        'Europe/Berlin'                  => '(GMT+01:00) Bern'                           ,
        'Europe/Bratislava'              => '(GMT+01:00) Bratislava'                     ,
        'Europe/Brussels'                => '(GMT+01:00) Brussels'                       ,
        'Europe/Budapest'                => '(GMT+01:00) Budapest'                       ,
        'Europe/Copenhagen'              => '(GMT+01:00) Copenhagen'                     ,
        'Europe/Ljubljana'               => '(GMT+01:00) Ljubljana'                      ,
        'Europe/Madrid'                  => '(GMT+01:00) Madrid'                         ,
        'Europe/Paris'                   => '(GMT+01:00) Paris'                          ,
        'Europe/Prague'                  => '(GMT+01:00) Prague'                         ,
        'Europe/Rome'                    => '(GMT+01:00) Rome'                           ,
        'Europe/Sarajevo'                => '(GMT+01:00) Sarajevo'                       ,
        'Europe/Skopje'                  => '(GMT+01:00) Skopje'                         ,
        'Europe/Stockholm'               => '(GMT+01:00) Stockholm'                      ,
        'Europe/Vienna'                  => '(GMT+01:00) Vienna'                         ,
        'Europe/Warsaw'                  => '(GMT+01:00) Warsaw'                         ,
        'Africa/Lagos'                   => '(GMT+01:00) West Central Africa'            ,
        'Europe/Zagreb'                  => '(GMT+01:00) Zagreb'                         ,
        'Europe/Athens'                  => '(GMT+02:00) Athens'                         ,
        'Europe/Bucharest'               => '(GMT+02:00) Bucharest'                      ,
        'Africa/Cairo'                   => '(GMT+02:00) Cairo'                          ,
        'Africa/Harare'                  => '(GMT+02:00) Harare'                         ,
        'Europe/Helsinki'                => '(GMT+02:00) Helsinki'                       ,
        'Europe/Istanbul'                => '(GMT+02:00) Istanbul'                       ,
        'Asia/Jerusalem'                 => '(GMT+02:00) Jerusalem'                      ,
        'Europe/Helsinki'                => '(GMT+02:00) Kyiv'                           ,
        'Africa/Johannesburg'            => '(GMT+02:00) Pretoria'                       ,
        'Europe/Riga'                    => '(GMT+02:00) Riga'                           ,
        'Europe/Sofia'                   => '(GMT+02:00) Sofia'                          ,
        'Europe/Tallinn'                 => '(GMT+02:00) Tallinn'                        ,
        'Europe/Vilnius'                 => '(GMT+02:00) Vilnius'                        ,
        'Asia/Baghdad'                   => '(GMT+03:00) Baghdad'                        ,
        'Asia/Kuwait'                    => '(GMT+03:00) Kuwait'                         ,
        'Europe/Minsk'                   => '(GMT+03:00) Minsk'                          ,
        'Africa/Nairobi'                 => '(GMT+03:00) Nairobi'                        ,
        'Asia/Riyadh'                    => '(GMT+03:00) Riyadh'                         ,
        'Europe/Volgograd'               => '(GMT+03:00) Volgograd'                      ,
        'Asia/Tehran'                    => '(GMT+03:30) Tehran'                         ,
        'Asia/Muscat'                    => '(GMT+04:00) Abu Dhabi'                      ,
        'Asia/Baku'                      => '(GMT+04:00) Baku'                           ,
        'Europe/Moscow'                  => '(GMT+04:00) Moscow'                         ,
        'Asia/Muscat'                    => '(GMT+04:00) Muscat'                         ,
        'Europe/Moscow'                  => '(GMT+04:00) St. Petersburg'                 ,
        'Asia/Tbilisi'                   => '(GMT+04:00) Tbilisi'                        ,
        'Asia/Yerevan'                   => '(GMT+04:00) Yerevan'                        ,
        'Asia/Kabul'                     => '(GMT+04:30) Kabul'                          ,
        'Asia/Karachi'                   => '(GMT+05:00) Islamabad'                      ,
        'Asia/Karachi'                   => '(GMT+05:00) Karachi'                        ,
        'Asia/Tashkent'                  => '(GMT+05:00) Tashkent'                       ,
        'Asia/Calcutta'                  => '(GMT+05:30) Chennai'                        ,
        'Asia/Kolkata'                   => '(GMT+05:30) Kolkata'                        ,
        'Asia/Calcutta'                  => '(GMT+05:30) Mumbai'                         ,
        'Asia/Calcutta'                  => '(GMT+05:30) New Delhi'                      ,
        'Asia/Calcutta'                  => '(GMT+05:30) Sri Jayawardenepura'            ,
        'Asia/Katmandu'                  => '(GMT+05:45) Kathmandu'                      ,
        'Asia/Almaty'                    => '(GMT+06:00) Almaty'                         ,
        'Asia/Dhaka'                     => '(GMT+06:00) Astana'                         ,
        'Asia/Dhaka'                     => '(GMT+06:00) Dhaka'                          ,
        'Asia/Yekaterinburg'             => '(GMT+06:00) Ekaterinburg'                   ,
        'Asia/Rangoon'                   => '(GMT+06:30) Rangoon'                        ,
        'Asia/Bangkok'                   => '(GMT+07:00) Bangkok'                        ,
        'Asia/Bangkok'                   => '(GMT+07:00) Hanoi'                          ,
        'Asia/Jakarta'                   => '(GMT+07:00) Jakarta'                        ,
        'Asia/Novosibirsk'               => '(GMT+07:00) Novosibirsk'                    ,
        'Asia/Hong_Kong'                 => '(GMT+08:00) Beijing'                        ,
        'Asia/Chongqing'                 => '(GMT+08:00) Chongqing'                      ,
        'Asia/Hong_Kong'                 => '(GMT+08:00) Hong Kong'                      ,
        'Asia/Krasnoyarsk'               => '(GMT+08:00) Krasnoyarsk'                    ,
        'Asia/Kuala_Lumpur'              => '(GMT+08:00) Kuala Lumpur'                   ,
        'Australia/Perth'                => '(GMT+08:00) Perth'                          ,
        'Asia/Singapore'                 => '(GMT+08:00) Singapore'                      ,
        'Asia/Taipei'                    => '(GMT+08:00) Taipei'                         ,
        'Asia/Ulan_Bator'                => '(GMT+08:00) Ulaan Bataar'                   ,
        'Asia/Urumqi'                    => '(GMT+08:00) Urumqi'                         ,
        'Asia/Irkutsk'                   => '(GMT+09:00) Irkutsk'                        ,
        'Asia/Tokyo'                     => '(GMT+09:00) Osaka'                          ,
        'Asia/Tokyo'                     => '(GMT+09:00) Sapporo'                        ,
        'Asia/Seoul'                     => '(GMT+09:00) Seoul'                          ,
        'Asia/Tokyo'                     => '(GMT+09:00) Tokyo'                          ,
        'Australia/Adelaide'             => '(GMT+09:30) Adelaide'                       ,
        'Australia/Darwin'               => '(GMT+09:30) Darwin'                         ,
        'Australia/Brisbane'             => '(GMT+10:00) Brisbane'                       ,
        'Australia/Canberra'             => '(GMT+10:00) Canberra'                       ,
        'Pacific/Guam'                   => '(GMT+10:00) Guam'                           ,
        'Australia/Hobart'               => '(GMT+10:00) Hobart'                         ,
        'Australia/Melbourne'            => '(GMT+10:00) Melbourne'                      ,
        'Pacific/Port_Moresby'           => '(GMT+10:00) Port Moresby'                   ,
        'Australia/Sydney'               => '(GMT+10:00) Sydney'                         ,
        'Asia/Yakutsk'                   => '(GMT+10:00) Yakutsk'                        ,
        'Asia/Vladivostok'               => '(GMT+11:00) Vladivostok'                    ,
        'Pacific/Auckland'               => '(GMT+12:00) Auckland'                       ,
        'Pacific/Fiji'                   => '(GMT+12:00) Fiji'                           ,
        'Pacific/Kwajalein'              => '(GMT+12:00) International Date Line West'   ,
        'Asia/Kamchatka'                 => '(GMT+12:00) Kamchatka'                      ,
        'Asia/Magadan'                   => '(GMT+12:00) Magadan'                        ,
        'Pacific/Fiji'                   => '(GMT+12:00) Marshall Is.'                   ,
        'Asia/Magadan'                   => '(GMT+12:00) New Caledonia'                  ,
        'Asia/Magadan'                   => '(GMT+12:00) Solomon Is.'                    ,
        'Pacific/Auckland'               => '(GMT+12:00) Wellington'                     ,
        'Pacific/Tongatapu'              => '(GMT+13:00) Nuku\'alofa'                    ,
    ];
    
    public static $colors = [
        "N/A"        => "Not Available",
        "beige"      => "Beige",
        "brown"      => "Brown",
        "lightbrown" => "Light Brown",
        "tan"        => "Tan",
        "black"      => "Black",
        "red"        => "Red",
        "blue"       => "Blue",
        "black"      => "Black",
        "gray"       => "Gray",
        "silver"     => "Silver",
        "charcoal"   => "Charcoal",
        "mocha"      => "Mocha",
    ];
    
    public static $yes_no = [
        "1" => "Yes",
        "0" => "No",
    ];
    
    public static $yes_no_string = [
        "Yes" => "Yes",
        "No" => "No",
    ];
    
    public static $true_false = [
        "True"  => "True",
        "False" => "False",
    ];
    
    public static $true_false_string = [
        "True"  => "True",
        "False" => "False",
    ];
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['countries', 'countryNames', 'languages', 'states', 'colors'], 'safe'],
        ];
    }
    
    //---------------------------------------------------------------------------------------------
    // description: Get the language string from the specified language code.
    // parameters : $lang_code (default 'en' for English)
    // return     : Language Name (string)
    //---------------------------------------------------------------------------------------------
    public static function getLanguage($lang_code='en')
    {
        if (!empty($lang_code)) {
            return self::$languages[$lang_code];
        } else {
            return Yii::t('app', "English");
        }
    }
    
    ///-------------------------------------------------------------------------
    /// <summary>
    /// Get Country ISO 3166_alpha2 from specified name
    /// </summary>
    /// <param>$aCountryName</param>
    /// <return>Array of countries_ISO3166_alpha2</return>
    ///-------------------------------------------------------------------------
    public static function getCountry_ISO3166_alpha2FromName($aCountryName)
    {
        return array_search($aCountryName, self::$countries_ISO3166_alpha2);
    }
    
    ///-------------------------------------------------------------------------
    /// <summary>
    /// Get Country ISO 3166_alpha3 from specified name
    /// </summary>
    /// <param>$aCountryName</param>
    /// <return>Array of countries_ISO3166_alpha3</return>
    ///-------------------------------------------------------------------------
    public static function getCountry_ISO3166_alpha3FromName($aCountryName)
    {
        return array_search($aCountryName, self::$countries_ISO3166_alpha3);
    }
    
    ///-------------------------------------------------------------------------
    /// <summary>
    /// Get Country ISO 3166_alpha2 from specified code
    /// </summary>
    /// <param>$aCountryCodeAlpha2</param>
    /// <return>Array of countries_ISO3166_alpha2</return>
    ///-------------------------------------------------------------------------
    public static function getNameFromCountry_ISO3166_alpha2($aCountryCodeAlpha2)
    {
        return self::$countries_ISO3166_alpha2[$aCountryCodeAlpha2];
    }
    
    ///-------------------------------------------------------------------------
    /// <summary>
    /// Get Country ISO 3166_alpha3 from specified code
    /// </summary>
    /// <param>$aCountryCodeAlpha3</param>
    /// <return>Array of countries_ISO3166_alpha3</return>
    ///-------------------------------------------------------------------------
    public static function getNameFromCountry_ISO3166_alpha3($aCountryCodeAlpha3)
    {
        return self::$countries_ISO3166_alpha3[$aCountryCodeAlpha3];
    }
    
    ///----------------------------------------------------------------------------------------
    /// <summary>
    /// Display the requested map in website.
    /// </summary>
    ///----------------------------------------------------------------------------------------
    public static function getMap($address, $mapProvider = 'google')
    {
        $querypreamble = "";
        switch($mapProvider) {
            default:
            case 'google':
                $querypreamble = "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q";
                break;
            case 'OpenStreeMap':
                // See more param doc: http://wiki.openstreetmap.org/wiki/Nominatim
                $querypreamble = "https://nominatim.openstreetmap.org/search?polygon=1&addressdetails=1&q";
                break;
        }

        $targetURL = "";
        // Example: 
        // - Address: Orlando, FL
        // - URL: http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=orlando,+fl
        if (!empty($address)) {
            $targetURL = "{$querypreamble}={$address}";
            return $targetURL;
        } else {
            // No address available.  Please enter a valid address to see the map.
            return '';
        }
    }

    ///----------------------------------------------------------------------------------------
    /// <summary>
    /// Convert standard US Time Zones to PHP equivalent. 
    /// </summary>
    ///----------------------------------------------------------------------------------------
    public static function getPhpTimeZone($aUSTimeZone)
    {
        // ------------------------------------------
        // US Time Zone            PHP Time Zone
        // ------------------------------------------
        // AST Atlantic........... America/Puerto_Rico
        // EST Eastern ........... America/New_York
        // CST Central ........... America/Chicago
        // MST Mountain .......... America/Denver
        // MST Mountain no DST ... America/Phoenix
        // PST Pacific ........... America/Los_Angeles
        // AKS Alaska ............ America/Anchorage
        // HST Hawaii ............ America/Adak
        // HST Hawaii no DST ..... Pacific/Honolulu
        // ------------------------------------------
        switch(strtoupper($aUSTimeZone)) {
            case 'AST':   $equivTimeZone = 'America/Puerto_Rico'; break;  // Atlantic Standard Time (AST)
            case 'EST':   $equivTimeZone = 'America/New_York';    break;  // Eastern Standard Time (EST)
            case 'CST':   $equivTimeZone = 'America/Chicago';     break;  // Central Standard Time (CST)
            case 'MST':   $equivTimeZone = 'America/Phoenix';     break;  // Mountain Standard Time (MST)
            case 'MST':   $equivTimeZone = 'America/Denver';      break;  // Mountain with Daylight Savings Time (MDT)
            case 'PST':   $equivTimeZone = 'America/Los_Angeles'; break;  // Pacific Standard Time (PST)
            case 'PDT':   $equivTimeZone = 'America/Los_Angeles'; break;  // Pacific with Daylight Savings Time (PDT)
            case 'AKS':   $equivTimeZone = 'America/Anchorage';   break;  // Alaska Standard Time (AKST)
            case 'AKST':  $equivTimeZone = 'America/Anchorage';   break;  // Alaska Standard Time (AKST)
            case 'AKDT':  $equivTimeZone = 'America/Anchorage';   break;  // Alaska with Daylight Savings Time (AKDT)
            case 'HST':   $equivTimeZone = 'Pacific/Honolulu';    break;  // Hawaii-Aleutian Standard Time (HAST)
            case 'HAST':  $equivTimeZone = 'Pacific/Honolulu';    break;  // Hawaii-Aleutian Standard Time (HAST)
            case 'HADT':  $equivTimeZone = 'America/Adak';        break;  // Hawaii-Aleutian with Daylight Savings Time (HADT)
            default:      $equivTimeZone = 'America/New_York';    break;
        }
        return $equivTimeZone;
    }
    
    public static function getGoogleTranslateDropdown()
    {
        //self::getGoogleTranslateDropdownV1();
        self::getGoogleTranslateDropdownV1LocalResources();
    }
    
    public static function getGoogleTranslateDropdownV2()
    { ?>
        <!-- GTranslate: https://gtranslate.io/ -->
        <a href="#" onclick="doGTranslate('en|en');return false;" title="English" class="gflag nturl" style="background-position:-0px -0px;">
        <img src="//gtranslate.net/flags/blank.png" height="16" width="16" alt="English" /></a>
        <a href="#" onclick="doGTranslate('en|fr');return false;" title="French" class="gflag nturl" style="background-position:-200px -100px;">
        <img src="//gtranslate.net/flags/blank.png" height="16" width="16" alt="French" /></a>
        <a href="#" onclick="doGTranslate('en|de');return false;" title="German" class="gflag nturl" style="background-position:-300px -100px;">
        <img src="//gtranslate.net/flags/blank.png" height="16" width="16" alt="German" /></a>
        <a href="#" onclick="doGTranslate('en|it');return false;" title="Italian" class="gflag nturl" style="background-position:-600px -100px;">
        <img src="//gtranslate.net/flags/blank.png" height="16" width="16" alt="Italian" /></a>
        <a href="#" onclick="doGTranslate('en|pt');return false;" title="Portuguese" class="gflag nturl" style="background-position:-300px -200px;">
        <img src="//gtranslate.net/flags/blank.png" height="16" width="16" alt="Portuguese" /></a>
        <a href="#" onclick="doGTranslate('en|ru');return false;" title="Russian" class="gflag nturl" style="background-position:-500px -200px;">
        <img src="//gtranslate.net/flags/blank.png" height="16" width="16" alt="Russian" /></a>
        <a href="#" onclick="doGTranslate('en|es');return false;" title="Spanish" class="gflag nturl" style="background-position:-600px -200px;">
        <img src="//gtranslate.net/flags/blank.png" height="16" width="16" alt="Spanish" /></a>

        <style type="text/css">
        <!--
        a.gflag {vertical-align:middle;font-size:16px;padding:1px 0;background-repeat:no-repeat;background-image:url(//gtranslate.net/flags/16.png);}
        a.gflag img {border:0;}
        a.gflag:hover {background-image:url(//gtranslate.net/flags/16a.png);}
        #goog-gt-tt {display:none !important;}
        .goog-te-banner-frame {display:none !important;}
        .goog-te-menu-value:hover {text-decoration:none !important;}
        body {top:0 !important;}
        #google_translate_element2 {display:none!important;}
        -->
        </style>

        <br /><select onchange="doGTranslate(this);"><option value="">Select Language</option><option value="en|af">Afrikaans</option><option value="en|sq">Albanian</option><option value="en|ar">Arabic</option><option value="en|hy">Armenian</option><option value="en|az">Azerbaijani</option><option value="en|eu">Basque</option><option value="en|be">Belarusian</option><option value="en|bg">Bulgarian</option><option value="en|ca">Catalan</option><option value="en|zh-CN">Chinese (Simplified)</option><option value="en|zh-TW">Chinese (Traditional)</option><option value="en|hr">Croatian</option><option value="en|cs">Czech</option><option value="en|da">Danish</option><option value="en|nl">Dutch</option><option value="en|en">English</option><option value="en|et">Estonian</option><option value="en|tl">Filipino</option><option value="en|fi">Finnish</option><option value="en|fr">French</option><option value="en|gl">Galician</option><option value="en|ka">Georgian</option><option value="en|de">German</option><option value="en|el">Greek</option><option value="en|ht">Haitian Creole</option><option value="en|iw">Hebrew</option><option value="en|hi">Hindi</option><option value="en|hu">Hungarian</option><option value="en|is">Icelandic</option><option value="en|id">Indonesian</option><option value="en|ga">Irish</option><option value="en|it">Italian</option><option value="en|ja">Japanese</option><option value="en|ko">Korean</option><option value="en|lv">Latvian</option><option value="en|lt">Lithuanian</option><option value="en|mk">Macedonian</option><option value="en|ms">Malay</option><option value="en|mt">Maltese</option><option value="en|no">Norwegian</option><option value="en|fa">Persian</option><option value="en|pl">Polish</option><option value="en|pt">Portuguese</option><option value="en|ro">Romanian</option><option value="en|ru">Russian</option><option value="en|sr">Serbian</option><option value="en|sk">Slovak</option><option value="en|sl">Slovenian</option><option value="en|es">Spanish</option><option value="en|sw">Swahili</option><option value="en|sv">Swedish</option><option value="en|th">Thai</option><option value="en|tr">Turkish</option><option value="en|uk">Ukrainian</option><option value="en|ur">Urdu</option><option value="en|vi">Vietnamese</option><option value="en|cy">Welsh</option><option value="en|yi">Yiddish</option></select><div id="google_translate_element2"></div>
        <script type="text/javascript">
        function googleTranslateElementInit2() {new google.translate.TranslateElement({pageLanguage: 'en',autoDisplay: false}, 'google_translate_element2');}
        </script><script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2"></script>


        <script type="text/javascript">
        /* <![CDATA[ */
        eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('6 7(a,b){n{4(2.9){3 c=2.9("o");c.p(b,f,f);a.q(c)}g{3 c=2.r();a.s(\'t\'+b,c)}}u(e){}}6 h(a){4(a.8)a=a.8;4(a==\'\')v;3 b=a.w(\'|\')[1];3 c;3 d=2.x(\'y\');z(3 i=0;i<d.5;i++)4(d[i].A==\'B-C-D\')c=d[i];4(2.j(\'k\')==E||2.j(\'k\').l.5==0||c.5==0||c.l.5==0){F(6(){h(a)},G)}g{c.8=b;7(c,\'m\');7(c,\'m\')}}',43,43,'||document|var|if|length|function|GTranslateFireEvent|value|createEvent||||||true|else|doGTranslate||getElementById|google_translate_element2|innerHTML|change|try|HTMLEvents|initEvent|dispatchEvent|createEventObject|fireEvent|on|catch|return|split|getElementsByTagName|select|for|className|goog|te|combo|null|setTimeout|500'.split('|'),0,{}))
        /* ]]> */
        </script>
    <?php
    }

    public static function getGoogleTranslateDropdownV1LocalResources()
    { ?>
        <!-- GTranslate: https://gtranslate.io/ -->
        <a href="#" onclick="doGTranslate('en|en');return false;" title="English" class="gflag nturl" style="background-position:-0px -0px;">
        <img src="https://cdn.auditiva.us/frontpage/flags/blank.png" height="16" width="16" alt="English" /></a>
        <a href="#" onclick="doGTranslate('en|fr');return false;" title="French" class="gflag nturl" style="background-position:-200px -100px;">
        <img src="https://cdn.auditiva.us/frontpage/flags/blank.png" height="16" width="16" alt="French" /></a>
        <a href="#" onclick="doGTranslate('en|de');return false;" title="German" class="gflag nturl" style="background-position:-300px -100px;">
        <img src="https://cdn.auditiva.us/frontpage/flags/blank.png" height="16" width="16" alt="German" /></a>
        <a href="#" onclick="doGTranslate('en|it');return false;" title="Italian" class="gflag nturl" style="background-position:-600px -100px;">
        <img src="https://cdn.auditiva.us/frontpage/flags/blank.png" height="16" width="16" alt="Italian" /></a>
        <a href="#" onclick="doGTranslate('en|pt');return false;" title="Portuguese" class="gflag nturl" style="background-position:-300px -200px;">
        <img src="https://cdn.auditiva.us/frontpage/flags/blank.png" height="16" width="16" alt="Portuguese" /></a>
        <a href="#" onclick="doGTranslate('en|ru');return false;" title="Russian" class="gflag nturl" style="background-position:-500px -200px;">
        <img src="https://cdn.auditiva.us/frontpage/flags/blank.png" height="16" width="16" alt="Russian" /></a>
        <a href="#" onclick="doGTranslate('en|es');return false;" title="Spanish" class="gflag nturl" style="background-position:-600px -200px;">
        <img src="https://cdn.auditiva.us/frontpage/flags/blank.png" height="16" width="16" alt="Spanish" /></a>

        <style type="text/css">
        <!--
        a.gflag {vertical-align:middle;font-size:16px;padding:1px 0;background-repeat:no-repeat;background-image:url(https://cdn.auditiva.us/frontpage/flags/16.png);}
        a.gflag img {border:0;}
        a.gflag:hover {background-image:url(https://cdn.auditiva.us/frontpage/flags/16a.png);}
        #goog-gt-tt {display:none !important;}
        .goog-te-banner-frame {display:none !important;}
        .goog-te-menu-value:hover {text-decoration:none !important;}
        body {top:0 !important;}
        #google_translate_element2 {display:none!important;}
        -->
        </style>

        <br /><select onchange="doGTranslate(this);"><option value="">Select Language</option><option value="en|af">Afrikaans</option><option value="en|sq">Albanian</option><option value="en|ar">Arabic</option><option value="en|hy">Armenian</option><option value="en|az">Azerbaijani</option><option value="en|eu">Basque</option><option value="en|be">Belarusian</option><option value="en|bg">Bulgarian</option><option value="en|ca">Catalan</option><option value="en|zh-CN">Chinese (Simplified)</option><option value="en|zh-TW">Chinese (Traditional)</option><option value="en|hr">Croatian</option><option value="en|cs">Czech</option><option value="en|da">Danish</option><option value="en|nl">Dutch</option><option value="en|en">English</option><option value="en|et">Estonian</option><option value="en|tl">Filipino</option><option value="en|fi">Finnish</option><option value="en|fr">French</option><option value="en|gl">Galician</option><option value="en|ka">Georgian</option><option value="en|de">German</option><option value="en|el">Greek</option><option value="en|ht">Haitian Creole</option><option value="en|iw">Hebrew</option><option value="en|hi">Hindi</option><option value="en|hu">Hungarian</option><option value="en|is">Icelandic</option><option value="en|id">Indonesian</option><option value="en|ga">Irish</option><option value="en|it">Italian</option><option value="en|ja">Japanese</option><option value="en|ko">Korean</option><option value="en|lv">Latvian</option><option value="en|lt">Lithuanian</option><option value="en|mk">Macedonian</option><option value="en|ms">Malay</option><option value="en|mt">Maltese</option><option value="en|no">Norwegian</option><option value="en|fa">Persian</option><option value="en|pl">Polish</option><option value="en|pt">Portuguese</option><option value="en|ro">Romanian</option><option value="en|ru">Russian</option><option value="en|sr">Serbian</option><option value="en|sk">Slovak</option><option value="en|sl">Slovenian</option><option value="en|es">Spanish</option><option value="en|sw">Swahili</option><option value="en|sv">Swedish</option><option value="en|th">Thai</option><option value="en|tr">Turkish</option><option value="en|uk">Ukrainian</option><option value="en|ur">Urdu</option><option value="en|vi">Vietnamese</option><option value="en|cy">Welsh</option><option value="en|yi">Yiddish</option></select>
        <div id="google_translate_element2"></div>
        <script type="text/javascript">
        function googleTranslateElementInit2() {new google.translate.TranslateElement({pageLanguage: 'za',autoDisplay: false}, 'google_translate_element2');}
        </script><script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2"></script>


        <script type="text/javascript">
        /* <![CDATA[ */
        eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('6 7(a,b){n{4(2.9){3 c=2.9("o");c.p(b,f,f);a.q(c)}g{3 c=2.r();a.s(\'t\'+b,c)}}u(e){}}6 h(a){4(a.8)a=a.8;4(a==\'\')v;3 b=a.w(\'|\')[1];3 c;3 d=2.x(\'y\');z(3 i=0;i<d.5;i++)4(d[i].A==\'B-C-D\')c=d[i];4(2.j(\'k\')==E||2.j(\'k\').l.5==0||c.5==0||c.l.5==0){F(6(){h(a)},G)}g{c.8=b;7(c,\'m\');7(c,\'m\')}}',43,43,'||document|var|if|length|function|GTranslateFireEvent|value|createEvent||||||true|else|doGTranslate||getElementById|google_translate_element2|innerHTML|change|try|HTMLEvents|initEvent|dispatchEvent|createEventObject|fireEvent|on|catch|return|split|getElementsByTagName|select|for|className|goog|te|combo|null|setTimeout|500'.split('|'),0,{}))
        /* ]]> */
        </script>
    <?php
    }
}
